export const SHOPS = {
  hardware: {
    id: 'hardware',
    name: 'Sharma Hardware & Electricals',
    tagline: 'Secunderabad, Hyderabad',
    lang: 'hi',
    logo: 'ti-tools',
    theme: {
      '--primary': '#185FA5',
      '--primary-light': '#E6F1FB',
      '--primary-dark': '#0C447C',
      '--accent': '#E8650A',
      '--header-bg': '#1A1208',
      '--header-text': '#fff',
      '--header-accent': '#E8650A',
    },
    seedItems: [
      {id:1,name:"GI Pipe",hi:"जीआई पाइप",cat:"Plumbing",unit:"ft",price:85,cost:60,stock:320},
      {id:2,name:"PVC Pipe",hi:"पीवीसी पाइप",cat:"Plumbing",unit:"ft",price:35,cost:22,stock:480},
      {id:3,name:"Copper Wire 2.5mm",hi:"तांबे का तार",cat:"Electrical",unit:"mtr",price:75,cost:55,stock:600},
      {id:4,name:"MCB Switch",hi:"एमसीबी स्विच",cat:"Electrical",unit:"pc",price:180,cost:120,stock:45},
      {id:5,name:"Cement Bag",hi:"सीमेंट",cat:"Construction",unit:"bag",price:380,cost:310,stock:8},
      {id:6,name:"M-Seal",hi:"एम-सील",cat:"Plumbing",unit:"pc",price:65,cost:40,stock:60},
      {id:7,name:'Paint Brush 4"',hi:"पेंट ब्रश",cat:"Paint",unit:"pc",price:90,cost:55,stock:30},
      {id:8,name:"Angle Grinder Disc",hi:"ग्राइंडर डिस्क",cat:"Tools",unit:"pc",price:120,cost:80,stock:3},
      {id:9,name:"3-pin Socket",hi:"सॉकेट",cat:"Electrical",unit:"pc",price:95,cost:60,stock:80},
      {id:10,name:"Nuts & Bolts Set",hi:"नट-बोल्ट",cat:"Fasteners",unit:"set",price:45,cost:25,stock:150},
      {id:11,name:"Plumber Tape",hi:"टेप",cat:"Plumbing",unit:"roll",price:25,cost:12,stock:90},
      {id:12,name:"WD-40 Spray",hi:"डब्ल्यूडी-40",cat:"Tools",unit:"can",price:320,cost:220,stock:2},
      {id:13,name:"Sandpaper",hi:"सैंडपेपर",cat:"Paint",unit:"sheet",price:15,cost:8,stock:200},
      {id:14,name:"Cable Ties",hi:"केबल टाई",cat:"Electrical",unit:"pack",price:55,cost:30,stock:0},
      {id:15,name:"CPVC Elbow",hi:"सीपीवीसी एल्बो",cat:"Plumbing",unit:"pc",price:28,cost:15,stock:180},
    ],
    seedContractors: [
      {name:"Raju Construction",hi:"राजू कंस्ट्रक्शन",balance:28400,limit:50000,lastPaid:"3 days ago",overdue:false},
      {name:"Suresh Builders",hi:"सुरेश बिल्डर्स",balance:45200,limit:40000,lastPaid:"18 days ago",overdue:true},
      {name:"Mahesh & Sons",hi:"महेश एंड संस",balance:12800,limit:30000,lastPaid:"1 day ago",overdue:false},
      {name:"Venkat Electricals",hi:"वेंकट इलेक्ट्रिकल्स",balance:8600,limit:20000,lastPaid:"5 days ago",overdue:false},
      {name:"Ram Plumbers",hi:"राम प्लंबर्स",balance:18900,limit:25000,lastPaid:"22 days ago",overdue:true},
      {name:"Lakshmi Interiors",hi:"लक्ष्मी इंटीरियर्स",balance:10600,limit:20000,lastPaid:"2 days ago",overdue:false},
    ],
    categories: ['Plumbing', 'Electrical', 'Construction', 'Paint', 'Tools', 'Fasteners'],
    units: ['pc', 'ft', 'mtr', 'bag', 'set', 'roll', 'can', 'sheet', 'pack'],
    expenseCategories: {
      loading: 'Loading coolie',
      transport: 'Auto / Transport',
      chai: 'Chai-Paani',
      electricity: 'Electricity',
      rent: 'Rent',
      salary: 'Staff salary',
      misc: 'Miscellaneous',
    },
  },

  kirana: {
    id: 'kirana',
    name: 'Sri Venkateswara Kirana',
    tagline: 'Kothapet, Hyderabad · Since 2005',
    lang: 'te',
    logo: 'ti-shopping-cart',
    theme: {
      '--primary': '#D97706',
      '--primary-light': '#FEF3C7',
      '--primary-dark': '#92400E',
      '--accent': '#059669',
      '--header-bg': '#1A1208',
      '--header-text': '#fff',
      '--header-accent': '#D97706',
    },
    seedItems: [
      {id:1,name:"Sonamasoori Rice",hi:"సోనా మసూరి బియ్యం",cat:"Staples",unit:"kg",price:58,cost:52,stock:200},
      {id:2,name:"Toor Dal",hi:"కంది పప్పు",cat:"Staples",unit:"kg",price:140,cost:125,stock:80},
      {id:3,name:"Sugar",hi:"చక్కెర",cat:"Staples",unit:"kg",price:42,cost:38,stock:150},
      {id:4,name:"Cooking Oil 1L",hi:"వంట నూనె",cat:"Staples",unit:"L",price:175,cost:158,stock:60},
      {id:5,name:"Wheat Flour (Atta)",hi:"గోధుమ పిండి",cat:"Staples",unit:"kg",price:35,cost:30,stock:100},
      {id:6,name:"Biscuits (Parle-G)",hi:"బిస్కెట్లు",cat:"Snacks",unit:"pack",price:10,cost:8,stock:300},
      {id:7,name:"Coca-Cola 300ml",hi:"కోకాకోలా",cat:"Beverages",unit:"bottle",price:35,cost:28,stock:120},
      {id:8,name:"Tea Powder 100g",hi:"టీ పొడి",cat:"Beverages",unit:"pack",price:45,cost:38,stock:50},
      {id:9,name:"Turmeric Powder",hi:"పసుపు",cat:"Spices",unit:"pack",price:25,cost:18,stock:90},
      {id:10,name:"Chilli Powder",hi:"కారం పొడి",cat:"Spices",unit:"pack",price:35,cost:28,stock:75},
      {id:11,name:"Soap",hi:"సబ్బు",cat:"Personal Care",unit:"pc",price:28,cost:22,stock:180},
      {id:12,name:"Shampoo Sachet",hi:"షాంపూ సాచెట్",cat:"Personal Care",unit:"pc",price:5,cost:4,stock:500},
      {id:13,name:"Toothpaste",hi:"టూత్పేస్ట్",cat:"Personal Care",unit:"tube",price:85,cost:72,stock:40},
      {id:14,name:"Candle",hi:"కొవ్వొత్తి",cat:"General",unit:"pc",price:10,cost:7,stock:0},
      {id:15,name:"Matchbox",hi:"మ్యాచ్ బాక్స్",cat:"General",unit:"box",price:5,cost:3,stock:200},
    ],
    seedContractors: [],
    categories: ['Staples', 'Snacks', 'Beverages', 'Spices', 'Personal Care', 'General'],
    units: ['kg', 'g', 'L', 'ml', 'pc', 'pack', 'bottle', 'box', 'tube'],
    expenseCategories: {
      transport: 'Transport',
      electricity: 'Electricity',
      rent: 'Rent',
      salary: 'Staff salary',
      misc: 'Miscellaneous',
    },
  },

  medical: {
    id: 'medical',
    name: 'Sai Krishna Medicals',
    tagline: 'Karmanghat, Hyderabad · Since 2012',
    lang: 'te',
    logo: 'ti-heartbeat',
    theme: {
      '--primary': '#0D9488',
      '--primary-light': '#CCFBF1',
      '--primary-dark': '#115E59',
      '--accent': '#2563EB',
      '--header-bg': '#134E4A',
      '--header-text': '#fff',
      '--header-accent': '#14B8A6',
    },
    seedItems: [
      {id:1,name:"Paracetamol 500mg",hi:"పారాసిటమాల్",cat:"Tablets",unit:"strip",price:25,cost:18,stock:200},
      {id:2,name:"Amoxicillin 500mg",hi:"అమోక్సిసిలిన్",cat:"Tablets",unit:"strip",price:85,cost:65,stock:120},
      {id:3,name:"Vitamin C 500mg",hi:"విటమిన్ సి",cat:"Supplements",unit:"strip",price:95,cost:75,stock:80},
      {id:4,name:"Cough Syrup",hi:"దగ్గు సిరప్",cat:"Syrups",unit:"bottle",price:120,cost:98,stock:45},
      {id:5,name:"Antacid Syrup",hi:"యాంటాసిడ్ సిరప్",cat:"Syrups",unit:"bottle",price:90,cost:72,stock:30},
      {id:6,name:"Band-Aid",hi:"బ్యాండ్ ఎయిడ్",cat:"First Aid",unit:"box",price:35,cost:25,stock:100},
      {id:7,name:"Dettol 100ml",hi:"డెట్టోల్",cat:"First Aid",unit:"bottle",price:68,cost:55,stock:60},
      {id:8,name:"Multivitamin Tablets",hi:"మల్టీవిటమిన్",cat:"Supplements",unit:"strip",price:150,cost:120,stock:70},
      {id:9,name:"Cetirizine 10mg",hi:"సిట్రిజిన్",cat:"Tablets",unit:"strip",price:30,cost:22,stock:150},
      {id:10,name:"Hand Sanitizer",hi:"హ్యాండ్ శానిటైజర్",cat:"First Aid",unit:"bottle",price:55,cost:40,stock:40},
      {id:11,name:"Omeprazole 20mg",hi:"ఓమెప్రజోల్",cat:"Tablets",unit:"strip",price:40,cost:30,stock:90},
      {id:12,name:"Sunscreen Lotion",hi:"సన్‌స్క్రీన్",cat:"Personal Care",unit:"tube",price:180,cost:145,stock:25},
      {id:13,name:"ORS Powder",hi:"ORS పొడి",cat:"Supplements",unit:"pack",price:20,cost:14,stock:200},
      {id:14,name:"Glucose-D",hi:"గ్లూకోజ్-డి",cat:"Supplements",unit:"pack",price:45,cost:35,stock:60},
      {id:15,name:"Sanitary Napkins",hi:"శానిటరీ నాప్కిన్స్",cat:"Personal Care",unit:"pack",price:95,cost:78,stock:0},
    ],
    seedContractors: [],
    categories: ['Tablets', 'Syrups', 'Supplements', 'First Aid', 'Personal Care'],
    units: ['strip', 'bottle', 'pc', 'box', 'tube', 'pack', 'spray'],
    expenseCategories: {
      electricity: 'Electricity',
      rent: 'Rent',
      salary: 'Staff salary',
      misc: 'Miscellaneous',
    },
  },

  stationary: {
    id: 'stationary',
    name: 'Mahalaxmi Stationary',
    tagline: 'Kothapet, Hyderabad · All your school needs',
    lang: 'en',
    logo: 'ti-news',
    theme: {
      '--primary': '#1E40AF',
      '--primary-light': '#DBEAFE',
      '--primary-dark': '#1E3A8A',
      '--accent': '#F59E0B',
      '--header-bg': '#1E40AF',
      '--header-text': '#fff',
      '--header-accent': '#F59E0B',
    },
    seedItems: [
      {id:1,name:"Reynolds Pen (Blue)",hi:"రేనాల్డ్స్ పెన్",cat:"Pens & Writing",unit:"pc",price:30,cost:22,stock:200},
      {id:2,name:"Reynolds Pen (Black)",hi:"రేనాల్డ్స్ పెన్ (బ్లాక్)",cat:"Pens & Writing",unit:"pc",price:30,cost:22,stock:180},
      {id:3,name:"Natraj Pencil",hi:"నాటరాజ్ పెన్సిల్",cat:"Pencils & Erasers",unit:"pc",price:5,cost:3,stock:500},
      {id:4,name:"Eraser (Doms)",hi:"ఎరేజర్",cat:"Pencils & Erasers",unit:"pc",price:8,cost:5,stock:300},
      {id:5,name:"Classmate Notebook (200pg)",hi:"నోట్‌బుక్",cat:"Notebooks & Pads",unit:"pc",price:75,cost:58,stock:100},
      {id:6,name:"Sharpener",hi:"షార్పనర్",cat:"Pencils & Erasers",unit:"pc",price:5,cost:3,stock:250},
      {id:7,name:"Fevicol 100ml",hi:"ఫెవికోల్",cat:"Art Supplies",unit:"bottle",price:35,cost:25,stock:60},
      {id:8,name:"Crayons (12 colors)",hi:"క్రేయాన్స్",cat:"Art Supplies",unit:"pack",price:45,cost:35,stock:40},
      {id:9,name:"White Paper Pack A4",hi:"వైట్ పేపర్",cat:"Office Supplies",unit:"pack",price:80,cost:62,stock:30},
      {id:10,name:"Stapler + Pins",hi:"స్టేప్లర్",cat:"Office Supplies",unit:"set",price:120,cost:95,stock:20},
      {id:11,name:"Cellotape",hi:"సెల్లోటేప్",cat:"Office Supplies",unit:"roll",price:15,cost:10,stock:80},
      {id:12,name:"Sketch Pens (12 colors)",hi:"స్కెచ్ పెన్స్",cat:"Art Supplies",unit:"pack",price:65,cost:50,stock:35},
      {id:13,name:"Geometry Box",hi:"జామెట్రీ బాక్స్",cat:"Art Supplies",unit:"pc",price:150,cost:118,stock:15},
      {id:14,name:"Ruler 15cm",hi:"స్కేల్",cat:"Office Supplies",unit:"pc",price:12,cost:8,stock:0},
      {id:15,name:"Paint Brush Set",hi:"పెయింట్ బ్రష్",cat:"Art Supplies",unit:"set",price:55,cost:42,stock:25},
    ],
    seedContractors: [],
    categories: ['Pens & Writing', 'Pencils & Erasers', 'Notebooks & Pads', 'Art Supplies', 'Office Supplies', 'Books'],
    units: ['pc', 'pack', 'set', 'bottle', 'roll', 'box'],
    expenseCategories: {
      electricity: 'Electricity',
      rent: 'Rent',
      salary: 'Staff salary',
      misc: 'Miscellaneous',
    },
  },

  pooja: {
    id: 'pooja',
    name: 'Shalini Pooja Store',
    tagline: 'Beside Ashta Laxmi Temple, Kothapet, Hyderabad',
    lang: 'te',
    logo: 'ti-flame',
    theme: {
      '--primary': '#7B1F2E',
      '--primary-light': '#FDF0E6',
      '--primary-dark': '#5C1521',
      '--accent': '#E8650A',
      '--header-bg': '#7B1F2E',
      '--header-text': '#fff',
      '--header-accent': '#E8650A',
    },
    seedItems: [
      {id:1,name:"Agarbatti",hi:"అగరబత్తి",cat:"Incense",unit:"pack",price:30,cost:22,stock:45},
      {id:2,name:"Camphor",hi:"కర్పూరం",cat:"Flame",unit:"box",price:25,cost:18,stock:60},
      {id:3,name:"Kumkum",hi:"కుంకుమ",cat:"Powder",unit:"pack",price:20,cost:14,stock:8},
      {id:4,name:"Haldi (Turmeric)",hi:"పసుపు",cat:"Powder",unit:"pack",price:15,cost:10,stock:12},
      {id:5,name:"Coconut",hi:"కొబ్బరి కాయ",cat:"Offerings",unit:"pc",price:25,cost:18,stock:30},
      {id:6,name:"Flowers (Mixed)",hi:"పూలు",cat:"Offerings",unit:"bunch",price:40,cost:30,stock:20},
      {id:7,name:"Deepam Oil",hi:"దీపం నూనె",cat:"Oil",unit:"bottle",price:55,cost:42,stock:3},
      {id:8,name:"Puja Plate",hi:"పూజ ప్లేట్",cat:"Utensils",unit:"pc",price:80,cost:60,stock:0},
      {id:9,name:"Matchbox",hi:"మ్యాచ్ బాక్స్",cat:"Flame",unit:"box",price:10,cost:7,stock:90},
      {id:10,name:"Sandalwood Sticks",hi:"గంధం",cat:"Incense",unit:"stick",price:60,cost:45,stock:5},
      {id:11,name:"Brass Diya",hi:"ఇత్తడి దీపం",cat:"Utensils",unit:"pc",price:120,cost:90,stock:15},
      {id:12,name:"Holy Water (Gangajal)",hi:"పవిత్ర జలం",cat:"Offerings",unit:"bottle",price:35,cost:25,stock:0},
      {id:13,name:"Neem Leaves",hi:"వేప ఆకులు",cat:"Offerings",unit:"bunch",price:20,cost:14,stock:10},
      {id:14,name:"Vibhuti",hi:"విభూతి",cat:"Powder",unit:"pack",price:25,cost:18,stock:22},
      {id:15,name:"Banana Leaf",hi:"అరటి ఆకు",cat:"Offerings",unit:"pc",price:15,cost:10,stock:2},
    ],
    seedContractors: [],
    categories: ['Incense', 'Flame', 'Powder', 'Offerings', 'Oil', 'Utensils'],
    units: ['pack', 'box', 'pc', 'bunch', 'bottle', 'stick'],
    expenseCategories: {
      transport: 'Transport',
      electricity: 'Electricity',
      rent: 'Rent',
      salary: 'Staff salary',
      misc: 'Miscellaneous',
    },
  },
}

export const SHOP_LIST = Object.keys(SHOPS)

export function getShopConfig(id) {
  return SHOPS[id] || SHOPS.hardware
}

export function getShopFromURL() {
  const params = new URLSearchParams(window.location.search)
  return getShopConfig(params.get('shop') || 'hardware')
}
